"use strict";
exports.__esModule = true;
exports.TOKEN_REFRESH_SUCCESS = 'TOKEN_REFRESH_SUCCESS';
exports.TOKEN_DELETE_SUCCESS = 'TOKEN_DELETE_SUCCESS';
exports.LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
exports.RESET_USER = 'RESET_USER';
exports.LOAD_USER_FAILED = 'LOAD_USER_FAILED';
