export const TOKEN_REFRESH_SUCCESS = 'TOKEN_REFRESH_SUCCESS';
export const TOKEN_DELETE_SUCCESS = 'TOKEN_DELETE_SUCCESS';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const RESET_USER = 'RESET_USER';
export const LOAD_USER_FAILED = 'LOAD_USER_FAILED';
